### ISSUE TITLE
Update API schema, document schema generation

### ISSUE THREAD

**Issue by chqr** [ewannema/mm_json_client#6]
Hello! Thanks for this gem, it's helped us quite a bit!

We realized today that the checked-in api schemas are not compatible with Men and Mice 9.1. It would be great if the checked-in api schemas could be upgraded, and the process for supplying custom api schemas was documented.

Happy to supply a PR for this if you'd like.

**Comment by ewannema** [comment]
@chqr glad you've found this useful. I'll look into updating the docs and the api schemas. It will probably take me a few days because I'll have to set up 9.1.

**Comment by ewannema** [comment]
@chqr I have pushed documentation and API definition updates. Can you review and let me know if the docs are clear enough and if the 9.x API is working as you expect?

**Comment by chqr** [comment]
Seems to be working with our Men and Mice instance. Thanks again!
